export const LANGUAGE_OPTIONS = [
  { value: "auto", label: "Auto Detect" },
  { value: "en", label: "English" },
  { value: "en-US", label: "English (US)" },
  { value: "en-GB", label: "English (UK)" },
  { value: "en-AU", label: "English (Australia)" },
  { value: "en-NZ", label: "English (New Zealand)" },
  { value: "en-IN", label: "English (India)" },
  { value: "zh", label: "Chinese (Mandarin, Simplified)" },
  { value: "zh-CN", label: "Chinese (Mandarin, Simplified, China)" },
  { value: "zh-Hans", label: "Chinese (Mandarin, Simplified, Hans)" },
  { value: "zh-TW", label: "Chinese (Mandarin, Traditional)" },
  { value: "zh-Hant", label: "Chinese (Mandarin, Traditional, Hant)" },
  { value: "es", label: "Spanish" },
  { value: "es-419", label: "Spanish (Latin America)" },
  { value: "fr", label: "French" },
  { value: "fr-CA", label: "French (Canada)" },
  { value: "de", label: "German" },
  { value: "el", label: "Greek" },
  { value: "hi", label: "Hindi" },
  { value: "hi-Latn", label: "Hindi (Latin script)" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "ko-KR", label: "Korean (Korea)" },
  { value: "pt", label: "Portuguese" },
  { value: "pt-BR", label: "Portuguese (Brazil)" },
  { value: "pt-PT", label: "Portuguese (Portugal)" },
  { value: "it", label: "Italian" },
  { value: "nl", label: "Dutch" },
  { value: "pl", label: "Polish" },
  { value: "ru", label: "Russian" },
  { value: "sv", label: "Swedish" },
  { value: "sv-SE", label: "Swedish (Sweden)" },
  { value: "da", label: "Danish" },
  { value: "da-DK", label: "Danish (Denmark)" },
  { value: "fi", label: "Finnish" },
  { value: "id", label: "Indonesian" },
  { value: "ms", label: "Malay" },
  { value: "tr", label: "Turkish" },
  { value: "uk", label: "Ukrainian" },
  { value: "bg", label: "Bulgarian" },
  { value: "cs", label: "Czech" },
  { value: "ro", label: "Romanian" },
  { value: "sk", label: "Slovak" },
  { value: "hu", label: "Hungarian" },
  { value: "no", label: "Norwegian" },
  { value: "vi", label: "Vietnamese" },
  { value: "babel", label: "Babel (Experimental)" },
] as const

export const LANGUAGE_VALUES = new Set(LANGUAGE_OPTIONS.map((option) => option.value))

export function getLanguageLabel(value: string | undefined): string {
  if (!value) return ""
  return LANGUAGE_OPTIONS.find((option) => option.value === value)?.label ?? value
}
